[package]
name = "diceroll"
version = "1.0.0"
authors = ["Jesse B. Hannah <jesse@jbhannah.net>"]
edition = "2018"

[dependencies]
cfg-if = "0.1"
clap = "2"
lazy_static = "1"
mockall = "0.7.0"
rand = "0.7.3"
regex = "1"
